name: Post Vercel Preview URL

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  preview:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Wait for Vercel Deployment
        run: sleep 20 # Let Vercel trigger and deploy

      - name: Get Vercel Deployments
        run: |
          DEPLOYMENTS=$(curl -s -H "Authorization: Bearer ${{ secrets.VERCEL_TOKEN }}" \
            "https://api.vercel.com/v6/deployments?projectId=${{ secrets.VERCEL_PROJECT_ID }}")

          # Get the latest deployment URL
          URL=$(echo $DEPLOYMENTS | jq -r '.deployments[0].url')

          echo "PREVIEW_URL=https://$URL" >> $GITHUB_ENV

      - name: Comment on PR
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: |
            🚀 Preview Deployment Ready!
            [View Preview](https://${{ env.PREVIEW_URL }})
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
